version: 2
snapshot:
  widths: [375, 1280, 1920]
  percy-css: |
    .docs--container {
      height:unset;
    }
    .docs--container .docs--content
    {
      height:unset;
      overflow-y:visible;
      overflow-x:visible;
    }
discovery:
  disable-cache: true
